# Generated by Django 5.0.3 on 2024-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_game_player_team_teamplayer_team_players_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='static/teams_logo/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(upload_to='static/tournaments_logo/'),
        ),
    ]
