# Generated by Django 5.0.3 on 2024-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_team_logo_alter_tournament_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='game',
            field=models.CharField(choices=[('dota_2', 'Dota 2'), ('csgo', 'Counter-Strike: Global Offensive'), ('lol', 'League of Legends')], default=1, max_length=255, verbose_name='Игра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(default=1, upload_to='static/games_logo/'),
            preserve_default=False,
        ),
    ]
